benchmark_equities: QQQ
benchmark_crypto: BTC-USD

assets:
  - symbol: BTC-USD
    asset_class: crypto
  - symbol: ETH-USD
    asset_class: crypto
  - symbol: SOL-USD
    asset_class: crypto
  - symbol: META
    asset_class: equity
  - symbol: NVDA
    asset_class: equity
  - symbol: MSFT
    asset_class: equity
  - symbol: AAPL
    asset_class: equity
  - symbol: AMZN
    asset_class: equity
  - symbol: GOOGL
    asset_class: equity
  - symbol: AVGO
    asset_class: equity
  - symbol: TSLA
    asset_class: equity
